/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.TelaVender;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author goldb
 */
public class FormularioTelaVenderVeiculoView extends javax.swing.JPanel {
    
    private TelaVenderVeiculoView tela;

    /**
     * Creates new form FormularioTelaVenderVeiculo
     */
    public FormularioTelaVenderVeiculoView() {
        initComponents();
        
        tipoCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "- Tipo -", "Automóvel", "Motocicleta", "Van"
        }));
        
        categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "- Categoria -", "POPULAR", "INTERMEDIARIO", "LUXO"
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        tipoCombo = new javax.swing.JComboBox<>();
        marcaCombo = new javax.swing.JComboBox<>();
        categoriaCombo = new javax.swing.JComboBox<>();

        jLabel7.setText("Buscar Veiculo");

        tipoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Tipo -" }));

        marcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Marca -" }));
        marcaCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                marcaComboMousePressed(evt);
            }
        });

        categoriaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Categoria -" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void marcaComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaComboMousePressed
        switch(tipoCombo.getSelectedItem().toString()) {
            case "Automóvel":
            marcaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                "- Marca -", "VW", "GM", "Fiat", "Mercedes",
            }));
            break;
            case "Motocicleta":
            marcaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                "- Marca -", "Honda", "Yamaha"
            }));
            break;
            case "Van":
            marcaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                "- Marca -", "VW", "Mercedes"
            }));
            break;
        }
    }//GEN-LAST:event_marcaComboMousePressed

    
    public String[] getVeiculoFiltro() {
        String[] veiculoDados = new String[3];
        veiculoDados[0] = marcaCombo.getSelectedItem().toString();
        veiculoDados[1] = categoriaCombo.getSelectedItem().toString();
        veiculoDados[2] = tipoCombo.getSelectedItem().toString();
        return veiculoDados;
    }
    
    void setTelaView(TelaVenderVeiculoView tela) {
        this.tela = tela;
    }
    
    public void limpaCampos() {
        tela.getTabelaView().limpaCampos();

        tipoCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "- Tipo -", "Automóvel", "Motocicleta", "Van"
        }));
        marcaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "- Marca -"
        }));
        categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "- Categoria -", "POPULAR", "INTERMEDIARIO", "LUXO"
        }));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoriaCombo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> marcaCombo;
    private javax.swing.JComboBox<String> tipoCombo;
    // End of variables declaration//GEN-END:variables

    
}
