/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.TelaCliente;

import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import locadora.model.Cliente;

/**
 *
 * @author goldb
 */
public class FormularioTelaClienteView extends javax.swing.JPanel {

    private Cliente clienteSelecionadoParaAtualizacao;
    
    /**
     * Creates new form FormularioTelaClienteView
     */
    public FormularioTelaClienteView() {
        initComponents();
        formataCampo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tNome = new javax.swing.JFormattedTextField();
        lRG = new javax.swing.JLabel();
        tRG = new javax.swing.JTextField();
        lSNome = new javax.swing.JLabel();
        tSobrenome = new javax.swing.JFormattedTextField();
        lCPF = new javax.swing.JLabel();
        tCPF = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lRua = new javax.swing.JLabel();
        tRua = new javax.swing.JTextField();
        lCidade = new javax.swing.JLabel();
        tCidade = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        tNumero = new javax.swing.JFormattedTextField();
        lUF = new javax.swing.JLabel();
        tUF = new javax.swing.JFormattedTextField();
        lCEP = new javax.swing.JLabel();
        tCEP = new javax.swing.JFormattedTextField();

        jPanel1.setBackground(new java.awt.Color(228, 228, 228));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lNome.setText("Nome:");

        tNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lRG.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lRG.setText("RG:");

        tRG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lSNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lSNome.setText("Sobrenome:");

        tSobrenome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lCPF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lCPF.setText("CPF:");

        tCPF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        lRua.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lRua.setText("Rua:");

        tRua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lCidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lCidade.setText("Cidade:");

        tCidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lNumero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lNumero.setText("Nº:");

        tNumero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lUF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lUF.setText("UF:");

        tUF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lCEP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lCEP.setText("CEP:");

        tCEP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lRua)
                                    .addComponent(lCidade))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tRua, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lRG)
                                        .addGap(39, 39, 39)
                                        .addComponent(tRG, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lSNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lCPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lNumero)
                                .addGap(20, 20, 20)
                                .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lUF)
                                .addGap(18, 18, 18)
                                .addComponent(tUF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(lCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSNome)
                    .addComponent(tSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tRG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lRG)
                    .addComponent(lCPF)
                    .addComponent(tCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lRua)
                        .addComponent(tRua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lNumero)
                                .addComponent(tNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lUF)
                                    .addComponent(tUF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lCEP)
                                    .addComponent(tCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lCidade))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public Cliente getClienteFormulario() {
        String nome = tNome.getText();
        String sobrenome = tSobrenome.getText();
        String cpf = tCPF.getText();
        String rg = tRG.getText();
        String endereco = tRua.getText() + "," + tNumero.getText().trim() + "," + tCidade.getText() + "," + tUF.getText() + "," + tCEP.getText();
        return new Cliente(nome,sobrenome,rg,cpf,endereco);
    }
    
    public void limparCampos() {
        tNome.setText("");
        tSobrenome.setText("");
        tCPF.setText("");
        tRG.setText("");
        tRua.setText("");
        tNumero.setText("");
        tCidade.setText("");
        tUF.setText("");
        tCEP.setText("");
        tNome.setEditable(true);
        tSobrenome.setEditable(true);
        tRG.setEditable(true);
        tCPF.setEditable(true);
    }
    
    public void formataCampo() {
        try {
            MaskFormatter maskN = new MaskFormatter("####");
            MaskFormatter maskUF = new MaskFormatter("UU");
            MaskFormatter maskCEP = new MaskFormatter("#####-###");
            maskN.install(tNumero);
            maskUF.install(tUF);
            maskCEP.install(tCEP);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "ERRO! Algum campo foi mal preenchido!");
        }
    }
    
    public void setCliente(Cliente cliente) {
        this.clienteSelecionadoParaAtualizacao = cliente;
        tNome.setText(cliente.getNome());
        tSobrenome.setText(cliente.getSobrenome());
        tRG.setText(cliente.getRG());
        tCPF.setText(cliente.getCPF());
        String[] endereco = cliente.getEndereco().split(",");
        tRua.setText(endereco[0]);
        tNumero.setText(endereco[1]);
        tCidade.setText(endereco[2]);
        tUF.setText(endereco[3]);
        tCEP.setText(endereco[4]);
        tNome.setEditable(false);
        tSobrenome.setEditable(false);
        tRG.setEditable(false);
        tCPF.setEditable(false); 
    }
    
    public Cliente getClienteParaAtualizar() {
        if(clienteSelecionadoParaAtualizacao == null){
            return null;
        }
        clienteSelecionadoParaAtualizacao.setNome(tNome.getText());
        clienteSelecionadoParaAtualizacao.setSobrenome(tSobrenome.getText());
        clienteSelecionadoParaAtualizacao.setCPF(tCPF.getText());
        clienteSelecionadoParaAtualizacao.setRG(tRG.getText());
        String endereco = tRua.getText() + "," + tNumero.getText().trim() + "," + tCidade.getText() + "," + tUF.getText() + "," + tCEP.getText();
        clienteSelecionadoParaAtualizacao.setEndereco(endereco);
        return clienteSelecionadoParaAtualizacao;      
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lCEP;
    private javax.swing.JLabel lCPF;
    private javax.swing.JLabel lCidade;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lRG;
    private javax.swing.JLabel lRua;
    private javax.swing.JLabel lSNome;
    private javax.swing.JLabel lUF;
    private javax.swing.JFormattedTextField tCEP;
    private javax.swing.JTextField tCPF;
    private javax.swing.JTextField tCidade;
    private javax.swing.JFormattedTextField tNome;
    private javax.swing.JFormattedTextField tNumero;
    private javax.swing.JTextField tRG;
    private javax.swing.JTextField tRua;
    private javax.swing.JFormattedTextField tSobrenome;
    private javax.swing.JFormattedTextField tUF;
    // End of variables declaration//GEN-END:variables
}
