/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.TelaCliente;

import java.util.ArrayList;
import java.util.List;
import locadora.model.Cliente;
import locadora.view.ClienteTableModel;

/**
 *
 * @author goldb
 */
public class TabelaTelaClienteView extends javax.swing.JPanel {
    private ClienteTableModel modeloTabela = new ClienteTableModel();
    private TelaClienteView tela;
    private int linhaClicadaParaAtualizacao = -1;
    

    /**
     * Creates new form TabelaTelaClienteView
     */
    public TabelaTelaClienteView() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        tabela.setModel(modeloTabela);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        linhaClicadaParaAtualizacao = this.tabela.rowAtPoint(evt.getPoint());
        Cliente cliente = modeloTabela.getCliente(linhaClicadaParaAtualizacao);
        tela.getFormularioClienteView().setCliente(cliente);
    }//GEN-LAST:event_tabelaMouseClicked

    public void setTelaView(TelaClienteView tela) {
        this.tela = tela;
    }
    
    public void atualizarClienteNaTabela(Cliente cliente) {
        modeloTabela.fireTableRowsUpdated(linhaClicadaParaAtualizacao, linhaClicadaParaAtualizacao);
    }
    
    public List<Cliente> getClientesParaExcluir() {
        int[] linhasSelecionadas = this.tabela.getSelectedRows();
        List<Cliente> listaExcluir = new ArrayList();
        for (int i = 0; i < linhasSelecionadas.length; i++) {
            Cliente cliente = modeloTabela.getCliente(linhasSelecionadas[i]);
            listaExcluir.add(cliente);
        }
        return listaExcluir;
    }
    
    public void excluirContatosDaTabela(List<Cliente> listaParaExcluir) {
        modeloTabela.removeClientes(listaParaExcluir);
    }
    
    public void inserirContatoTabela(Cliente cliente) {
        modeloTabela.adicionaCliente(cliente);
    }
    
    public void setListaClientesTabela(List<Cliente> lista) {
        modeloTabela.setListaClientes(lista);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
