/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view.TelaCliente;

import java.util.List;
import javax.swing.JOptionPane;
import locadora.controller.ClienteController;
import locadora.model.Cliente;

/**
 *
 * @author goldb
 */
public class TelaClienteView extends javax.swing.JFrame {

    /**
     * Creates new form NewTelaClienteView
     */
    public TelaClienteView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabelaTelaClienteView = new locadora.view.TelaCliente.TabelaTelaClienteView();
        botoesTelaClienteView = new locadora.view.TelaCliente.BotoesTelaClienteView();
        formularioTelaClienteView = new locadora.view.TelaCliente.FormularioTelaClienteView();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Clientes");

        tabelaTelaClienteView.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botoesTelaClienteView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formularioTelaClienteView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tabelaTelaClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formularioTelaClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botoesTelaClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaTelaClienteView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initView() {
        tabelaTelaClienteView.setTelaView(this);
        java.awt.EventQueue.invokeLater(() ->  this.setVisible(true));
    }
    
    public void setController(ClienteController controller) {
        botoesTelaClienteView.setController(controller);
    }
    
    public Cliente getClienteFormulario() {
        return this.formularioTelaClienteView.getClienteFormulario();
    }
    
    public void limparCampos() {
        this.formularioTelaClienteView.limparCampos();
    }
    
    
    public void formataCampo() {
        this.formularioTelaClienteView.formataCampo();
    }
    
    
    public void setCliente(Cliente cliente) {
        this.formularioTelaClienteView.setCliente(cliente);
    }
    
    public Cliente getClienteParaAtualizar() {
        return this.formularioTelaClienteView.getClienteParaAtualizar();
    }
    
    public void atualizarClienteNaTabela(Cliente cliente) {
        this.tabelaTelaClienteView.atualizarClienteNaTabela(cliente);
    }
    
    public List<Cliente> getClientesParaExcluir() {
        return this.tabelaTelaClienteView.getClientesParaExcluir();
    }
    
    public void excluirContatosDaTabela(List<Cliente> listaParaExcluir) {
        this.tabelaTelaClienteView.excluirContatosDaTabela(listaParaExcluir);
    }
    
    public void inserirContatoTabela(Cliente cliente) {
        this.tabelaTelaClienteView.inserirContatoTabela(cliente);
    }
    
    public void setListaClientesTabela(List<Cliente> lista) {
        this.tabelaTelaClienteView.setListaClientesTabela(lista);
    }
    
    public FormularioTelaClienteView getFormularioClienteView() {
        return formularioTelaClienteView;
    } 
    
    public void apresentaInfo(String info) {
        JOptionPane.showMessageDialog(null,info + "\n", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void apresentaErro(String erro) {
        JOptionPane.showMessageDialog(null,erro + "\n", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private locadora.view.TelaCliente.BotoesTelaClienteView botoesTelaClienteView;
    private locadora.view.TelaCliente.FormularioTelaClienteView formularioTelaClienteView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private locadora.view.TelaCliente.TabelaTelaClienteView tabelaTelaClienteView;
    // End of variables declaration//GEN-END:variables
}
