/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.TelaAlugar;

import java.text.ParseException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import locadora.model.Cliente;

/**
 *
 * @author goldb
 */
public class FormularioTelaAlugarVeiculoView extends javax.swing.JPanel {

    private TelaAlugarVeiculoView tela;
    /**
     * Creates new form FormularioTelaAlugarVeiculoView
     */
    public FormularioTelaAlugarVeiculoView() {
        initComponents();
        formataData();

        tipoCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "- Tipo -", "Automóvel", "Motocicleta", "Van"
        }));

        categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "- Categoria -", "POPULAR", "INTERMEDIARIO", "LUXO"
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        tBusca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tSNome = new javax.swing.JTextField();
        categoriaCombo = new javax.swing.JComboBox<>();
        marcaCombo = new javax.swing.JComboBox<>();
        tipoCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tDataLocacao = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tDiasLocacao = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        tBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setText("Cliente CPF:");

        jLabel3.setText("Nome:");

        tNome.setEditable(false);
        tNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setText("Sobrenome:");

        tSNome.setEditable(false);
        tSNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        categoriaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Categoria -" }));

        marcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Marca -" }));
        marcaCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                marcaComboMousePressed(evt);
            }
        });

        tipoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Tipo -" }));

        jLabel7.setText("Veiculo");

        jLabel6.setText("Data:");

        tDataLocacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setText("Dias de Locação:");

        tDiasLocacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tBusca))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(52, 52, 52)
                                .addComponent(tDataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(38, 38, 38)
                                .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(marcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tDiasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tSNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tDiasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void marcaComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaComboMousePressed
        switch (tipoCombo.getSelectedItem().toString()) {
            case "Automóvel":
                marcaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                    "- Marca -", "VW", "GM", "Fiat", "Mercedes",}));
                break;
            case "Motocicleta":
                marcaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                    "- Marca -", "Honda", "Yamaha"
                }));
                break;
            case "Van":
                marcaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                    "- Marca -", "VW", "Mercedes"
                }));
                break;
        }
    }//GEN-LAST:event_marcaComboMousePressed

    public String getClienteCPF() {
        return tBusca.getText();
    }
    
    public void apresentaCliente(Cliente c) {
        tNome.setText(c.getNome());
        tSNome.setText(c.getSobrenome());
    }
    
    public String[] getVeiculoFiltro() {
        String[] veiculoDados = new String[3];
        veiculoDados[0] = marcaCombo.getSelectedItem().toString();
        veiculoDados[1] = categoriaCombo.getSelectedItem().toString();
        veiculoDados[2] = tipoCombo.getSelectedItem().toString();
        return veiculoDados;
    }
    
    public String getDataLocacao() {
        return tDataLocacao.getText();
    }

    public String getDiasLocacao() {
        return tDiasLocacao.getText();
    }

    public void formataData() {
        try {
            MaskFormatter mask = new MaskFormatter("##/##/####");
            mask.install(tDataLocacao);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Data inserida está incorreta");
        }
    }

    public void limpaCampos() {
        tela.getTabelaView().limpaCampos();
        tBusca.setText("");
        tNome.setText("");
        tSNome.setText("");
        tDiasLocacao.setText("");
        tDataLocacao.setText("");

        tipoCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "- Tipo -", "Automóvel", "Motocicleta", "Van"
        }));
        marcaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "- Marca -"
        }));
        categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "- Categoria -", "POPULAR", "INTERMEDIARIO", "LUXO"
        }));
    }
    
    void setTelaView(TelaAlugarVeiculoView tela) {
        this.tela = tela;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoriaCombo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> marcaCombo;
    private javax.swing.JTextField tBusca;
    private javax.swing.JFormattedTextField tDataLocacao;
    private javax.swing.JTextField tDiasLocacao;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tSNome;
    private javax.swing.JComboBox<String> tipoCombo;
    // End of variables declaration//GEN-END:variables
}
