/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhofinal;

import trabalhofinal.Veiculo.Marca;
import trabalhofinal.Veiculo.ModeloVan;
import trabalhofinal.Veiculo.Estado;
import trabalhofinal.Veiculo.Motocicleta;
import trabalhofinal.Veiculo.ModeloAutomovel;
import trabalhofinal.Veiculo.Veiculo;
import trabalhofinal.Veiculo.Van;
import trabalhofinal.Veiculo.ModeloMotocicleta;
import trabalhofinal.Veiculo.Automovel;
import trabalhofinal.Veiculo.Categoria;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author goldb
 */
public class TelaComprarVeiculo extends javax.swing.JFrame {
     private TelaInicial locadora;
    /**
     * Creates new form ComprarVeiculo
     */
    public TelaComprarVeiculo() {
        initComponents();
        this.setLocationRelativeTo(null);
        formataCampo();
        
        marcaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "--- Selecione Marca ---", "VW", "GM", "Fiat",  "Honda",  "Mercedes", "Yamaha"
        }));
        
        estadoCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "--- Selecione Estado ---", "DISPONIVEL"
        }));
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        marcaCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        estadoCombo = new javax.swing.JComboBox<>();
        lModelo = new javax.swing.JLabel();
        modeloCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        categoriaCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bIncluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tAno = new javax.swing.JFormattedTextField();
        tValor = new javax.swing.JFormattedTextField();
        tPlaca = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comprar Veiculo");

        jLabel2.setText("Marca");

        marcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Selecione Marca ---" }));
        marcaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaComboActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado");

        estadoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Selecione Estado ---" }));

        lModelo.setText("Modelo");

        modeloCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Selecione Modelo ---" }));
        modeloCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeloComboMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modeloComboMousePressed(evt);
            }
        });
        modeloCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Categoria");

        categoriaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Selecione Categoria ---" }));
        categoriaCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoriaComboMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                categoriaComboMousePressed(evt);
            }
        });

        jLabel5.setText("Valor");

        jLabel6.setText("Placa");
        jLabel6.setToolTipText("");

        bIncluir.setText("Incluir Veiculo");
        bIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bIncluirMouseClicked(evt);
            }
        });

        jLabel7.setText("Ano");

        tAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(lModelo)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tAno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(marcaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estadoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modeloCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoriaCombo, 0, 354, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(marcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lModelo)
                    .addComponent(modeloCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estadoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marcaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaComboActionPerformed

    private void modeloComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloComboActionPerformed

    }//GEN-LAST:event_modeloComboActionPerformed

    private void modeloComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeloComboMouseClicked
        
    }//GEN-LAST:event_modeloComboMouseClicked

    private void modeloComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeloComboMousePressed
        switch(marcaCombo.getSelectedItem().toString()) {
            case "VW":
                modeloCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Modelo ---", "Gol", "Kombi", "Nivus"
                }));
                break;
            case "GM":
                modeloCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Modelo ---", "Celta"
                }));
                break;
            case "Fiat":
                modeloCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Modelo ---", "Palio", "Pulse"
                }));
                break;
            case "Honda":
                modeloCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Modelo ---", "BIZ", "TWISTER"
                }));
                break;
            case "Mercedes":
                modeloCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Modelo ---", "Sprinter", "Sedan"
                }));
                break;
            case "Yamaha":
                modeloCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Modelo ---", "FAZER", "CROSSER"
                }));
                break;
            default:
                modeloCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Modelo ---", "Nenhuma Marca foi selecionada" 
                }));
        }
    }//GEN-LAST:event_modeloComboMousePressed

    private void categoriaComboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaComboMouseEntered
        
    }//GEN-LAST:event_categoriaComboMouseEntered

    private void categoriaComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaComboMousePressed
        switch(modeloCombo.getSelectedItem().toString()) {
            case "Gol":
            case "Celta":
            case "Kombi":
            case "BIZ":
            case "Palio":
                categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Categoria ---", "POPULAR" 
                }));
                break;
            case "FAZER":
            case "CROSSER":
            case "TWISTER":
            case "Sprinter":
                categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Categoria ---", "INTERMEDIARIO" 
                }));
                break;
            case "Sedan":
            case "Pulse":
            case "Nivus":
                categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Categoria ---", "LUXO" 
                }));
                break;
            default:
                categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                    "--- Selecione Categoria ---", "Nenhum modelo foi selecionado" 
                }));
        }
        
    }//GEN-LAST:event_categoriaComboMousePressed

    private void bIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIncluirMouseClicked
        Marca marca = null;
        Estado estado = null;
        Categoria categoria = null;
        double valor = 0;
        int ano = 0;
        String placa = "";
        String modelo = "";
        try {
            marca = Marca.valueOf(marcaCombo.getSelectedItem().toString());
            estado = Estado.valueOf(estadoCombo.getSelectedItem().toString());
            categoria = Categoria.valueOf(categoriaCombo.getSelectedItem().toString());
            valor = Double.parseDouble(tValor.getText());
            ano = Integer.parseInt(tAno.getText());
            placa = tPlaca.getText();
            modelo = modeloCombo.getSelectedItem().toString();
        }
        catch (Exception err) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para realizar a compra!");
        }


        if (placa.equals("   -    ")) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para realizar a compra!");
        } 
        else if (ano > 2022 || ano < 1960) {
            JOptionPane.showMessageDialog(this, "Insira um ano válido!");
        }
        else {
            switch(modelo) {
                case "Gol":
                case "Celta":
                case "Palio":
                case "Nivus":   
                case "Pulse": 
                case "Sedan":
                    try {
                        ModeloAutomovel enumA = ModeloAutomovel.valueOf(modelo);
                        this.adicionaVeiculo(new Automovel(marca, estado, null, categoria, valor, placa, ano, enumA));
                        JOptionPane.showMessageDialog(this, "Automovel inserido com sucesso");
                        limparCampos();
                    }
                    catch (Exception err) {
                        JOptionPane.showMessageDialog(this, "Preencha todos os campos para realizar a compra!");
                    }
                    break;
                case "FAZER":
                case "CROSSER":
                case "BIZ":
                case "TWISTER":
                    try {
                        ModeloMotocicleta enumM = ModeloMotocicleta.valueOf(modelo);
                        this.adicionaVeiculo(new Motocicleta(marca, estado, null, categoria, valor, placa, ano, enumM));
                        JOptionPane.showMessageDialog(this, "Motocicleta inserida com sucesso");
                        limparCampos();
                    }
                    catch (Exception err) {
                        JOptionPane.showMessageDialog(this, "Preencha todos os campos para realizar a compra!");
                    }
                    break;
                case "Kombi":
                case "Sprinter":
                    try {
                        ModeloVan enumV = ModeloVan.valueOf(modelo);
                        this.adicionaVeiculo(new Van(marca, estado, null, categoria, valor, placa, ano, enumV));
                        JOptionPane.showMessageDialog(this, "Van inserida com sucesso");
                        limparCampos();
                    }
                    catch (Exception err) {
                        JOptionPane.showMessageDialog(this, "Preencha todos os campos para realizar a compra!");
                    }
                    break;     
            }
        }
        
        
       
    }//GEN-LAST:event_bIncluirMouseClicked

    private void tAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAnoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void init(TelaInicial locadora) {
        this.locadora = locadora;
        TelaComprarVeiculo inicial = this;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                inicial.setVisible(true);
            }
        });
    }
    
    void adicionaVeiculo(Veiculo f) {
        this.locadora.adicionaVeiculo(f);
    }
    
    private void formataCampo() {
        try {
            MaskFormatter maskA = new MaskFormatter("####");
            MaskFormatter maskV = new MaskFormatter("########");
            MaskFormatter maskP = new MaskFormatter("UUU-####");
            maskP.install(tPlaca);
            maskV.install(tValor);
            maskA.install(tAno);
        }
        catch (Exception err) {
            JOptionPane.showMessageDialog(this, "ERRO! Algum campo foi mal preenchido!");
        }
    }
    
    private void limparCampos() {
        marcaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "--- Selecione Marca ---", "VW", "GM", "Fiat",  "Honda",  "Mercedes", "Yahama"
        }));
        modeloCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "--- Selecione Modelo ---"
        }));
        estadoCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "--- Selecione Estado ---", "DISPONIVEL"
        }));
        categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "--- Selecione Categoria ---"
        }));
        tValor.setText("");
        tPlaca.setText("");
        tAno.setText("");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIncluir;
    private javax.swing.JComboBox<String> categoriaCombo;
    private javax.swing.JComboBox<String> estadoCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lModelo;
    private javax.swing.JComboBox<String> marcaCombo;
    private javax.swing.JComboBox<String> modeloCombo;
    private javax.swing.JFormattedTextField tAno;
    private javax.swing.JFormattedTextField tPlaca;
    private javax.swing.JFormattedTextField tValor;
    // End of variables declaration//GEN-END:variables
}

