/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhofinal;

import trabalhofinal.Veiculo.Veiculo;
import trabalhofinal.Tabelas.VeiculoVenderTableModel;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author goldb
 */
public class TelaVenderVeiculo extends javax.swing.JFrame {
    VeiculoVenderTableModel vvModeloTabela = new VeiculoVenderTableModel();
    private TelaInicial locadora;
    
    /**
     * Creates new form TelaVenderVeiculo
     */
    public TelaVenderVeiculo() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        tipoCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "- Tipo -", "Automóvel", "Motocicleta", "Van"
        }));
        
        categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
            "- Categoria -", "POPULAR", "INTERMEDIARIO", "LUXO"
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTabela = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tipoCombo = new javax.swing.JComboBox<>();
        marcaCombo = new javax.swing.JComboBox<>();
        categoriaCombo = new javax.swing.JComboBox<>();
        bFiltrar = new javax.swing.JButton();
        bVender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vender Veiculo");

        tTabela.setModel(vvModeloTabela);
        jScrollPane1.setViewportView(tTabela);

        jLabel7.setText("Buscar Veiculo");

        tipoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Tipo -" }));
        tipoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoComboActionPerformed(evt);
            }
        });

        marcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Marca -" }));
        marcaCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                marcaComboMousePressed(evt);
            }
        });

        categoriaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Categoria -" }));

        bFiltrar.setText("Filtrar");
        bFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarActionPerformed(evt);
            }
        });

        bVender.setText("Vender");
        bVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bVenderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(bFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bVender, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFiltrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bVender, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoComboActionPerformed

    private void marcaComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaComboMousePressed
        switch(tipoCombo.getSelectedItem().toString()) {
            case "Automóvel":
            marcaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                "- Marca -", "VW", "GM", "Fiat", "Mercedes",
            }));
            break;
            case "Motocicleta":
            marcaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                "- Marca -", "Honda", "Yamaha"
            }));
            break;
            case "Van":
            marcaCombo.setModel(new DefaultComboBoxModel<>(new String[] {
                "- Marca -", "VW", "Mercedes"
            }));
            break;
        }
    }//GEN-LAST:event_marcaComboMousePressed

    private void bFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarActionPerformed
        vvModeloTabela.limpaTabela();
        List<Veiculo> list = locadora.getVeiculos();
        String tipo = tipoCombo.getSelectedItem().toString();
        String marca = marcaCombo.getSelectedItem().toString();
        String categoria = categoriaCombo.getSelectedItem().toString();
        vvModeloTabela.setListaVeiculos(list, tipo, marca, categoria);
    }//GEN-LAST:event_bFiltrarActionPerformed

    private void bVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVenderMouseClicked
        List<Veiculo> listaVeiculos = this.locadora.getVeiculos();
        int row;
        String placa = "";
        try {
            row = tTabela.getSelectedRow();
            placa = (tTabela.getModel().getValueAt(row, 0)).toString();
        }
        catch (Exception err) {
            JOptionPane.showMessageDialog(this, "Nenhum veículo foi selecionado!");
        }

        Veiculo veiculo = null;
        for (Veiculo v : listaVeiculos) {
            if (v.getPlaca().equals(placa)) {
                veiculo = v;
            }
        }
        
        if (veiculo != null) {
            veiculo.vender();
            JOptionPane.showMessageDialog(this, "Veiculo vendido com Sucesso!");
            vvModeloTabela.removeVeiculo(veiculo);
            vvModeloTabela.limpaTabela();
            
        }
    }//GEN-LAST:event_bVenderMouseClicked

    /**
     * @param args the command line arguments
     */
    public void init(TelaInicial locadora) {
        this.locadora = locadora;
        TelaVenderVeiculo inicial = this;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                inicial.setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFiltrar;
    private javax.swing.JButton bVender;
    private javax.swing.JComboBox<String> categoriaCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> marcaCombo;
    private javax.swing.JTable tTabela;
    private javax.swing.JComboBox<String> tipoCombo;
    // End of variables declaration//GEN-END:variables
}
