/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import locadora.controller.ClienteController;
import locadora.controller.VeiculoController;
import locadora.model.dao.ClienteDAO;
import locadora.model.dao.ConnectionFactory;
import locadora.model.dao.VeiculoDAO;
import locadora.view.TelaAlugar.TelaAlugarVeiculoView;
import locadora.view.TelaCliente.TelaClienteView;
import locadora.view.TelaComprar.TelaComprarVeiculoView;
import locadora.view.TelaDevolver.TelaDevolverVeiculoView;
import locadora.view.TelaVender.TelaVenderVeiculoView;

/**
 *
 * @author goldb
 */
public class TelaInicialView extends javax.swing.JFrame {
    private ClienteDAO cDao = new ClienteDAO(new ConnectionFactory());
    private VeiculoDAO vDao = new VeiculoDAO(new ConnectionFactory());

    /**
     * Creates new form TelaInicial
     */
    public TelaInicialView() {
        initComponents();
        initView();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cliente = new javax.swing.JMenu();
        mNovoVeiculo = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mDevolver = new javax.swing.JMenu();
        mVender = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.red);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("GOLD LOCADORA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/locadora/view/banner-home5.png"))); // NOI18N

        cliente.setText("Clientes");
        cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(cliente);

        mNovoVeiculo.setText("Novo Veiculo");
        mNovoVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mNovoVeiculoMouseClicked(evt);
            }
        });
        jMenuBar1.add(mNovoVeiculo);

        jMenu3.setText("Alugar Veiculo");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        mDevolver.setText("Devolver Veiculo");
        mDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDevolverMouseClicked(evt);
            }
        });
        jMenuBar1.add(mDevolver);

        mVender.setText("Vender Veiculo");
        mVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mVenderMouseClicked(evt);
            }
        });
        jMenuBar1.add(mVender);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMouseClicked
        new ClienteController(new TelaClienteView(), cDao);
    }//GEN-LAST:event_clienteMouseClicked

    private void mNovoVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mNovoVeiculoMouseClicked
        new VeiculoController(new TelaComprarVeiculoView(), vDao);
        
    }//GEN-LAST:event_mNovoVeiculoMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        new VeiculoController(new TelaAlugarVeiculoView(), vDao);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void mDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDevolverMouseClicked
        new VeiculoController(new TelaDevolverVeiculoView(), vDao);
    }//GEN-LAST:event_mDevolverMouseClicked

    private void mVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mVenderMouseClicked
        new VeiculoController(new TelaVenderVeiculoView(), vDao);
    }//GEN-LAST:event_mVenderMouseClicked

 
    public void initView() {
        java.awt.EventQueue.invokeLater(() ->  this.setVisible(true));
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mDevolver;
    private javax.swing.JMenu mNovoVeiculo;
    private javax.swing.JMenu mVender;
    // End of variables declaration//GEN-END:variables

    
}
