/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.TelaComprar;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import locadora.model.Automovel;
import locadora.model.Categoria;
import locadora.model.Estado;
import locadora.model.Marca;
import locadora.model.ModeloAutomovel;
import locadora.model.ModeloMotocicleta;
import locadora.model.ModeloVan;
import locadora.model.Motocicleta;
import locadora.model.Van;
import locadora.model.Veiculo;

/**
 *
 * @author goldb
 */
public class FormularioTelaComprarVeiculoView extends javax.swing.JPanel {

    /**
     * Creates new form FormularioTelaComprarVeiculoView
     */
    public FormularioTelaComprarVeiculoView() {
        initComponents();
        formataCampo();
        marcaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "--- Selecione Marca ---", "VW", "GM", "Fiat", "Honda", "Mercedes", "Yamaha"
        }));

        estadoCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "--- Selecione Estado ---", "DISPONIVEL"
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        marcaCombo = new javax.swing.JComboBox<>();
        modeloCombo = new javax.swing.JComboBox<>();
        lModelo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estadoCombo = new javax.swing.JComboBox<>();
        categoriaCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tAno = new javax.swing.JFormattedTextField();
        tValor = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tPlaca = new javax.swing.JFormattedTextField();

        jLabel2.setText("Marca:");

        marcaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Selecione Marca ---" }));

        modeloCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Selecione Modelo ---" }));
        modeloCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modeloComboMousePressed(evt);
            }
        });

        lModelo.setText("Modelo:");

        jLabel3.setText("Estado:");

        estadoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Selecione Estado ---" }));

        categoriaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Selecione Categoria ---" }));
        categoriaCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                categoriaComboMousePressed(evt);
            }
        });

        jLabel4.setText("Categoria:");

        jLabel7.setText("Ano:");

        tAno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tValor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setText("Valor:");

        jLabel6.setText("Placa:");
        jLabel6.setToolTipText("");

        tPlaca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lModelo)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tAno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(modeloCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoriaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estadoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marcaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lModelo)
                    .addComponent(modeloCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estadoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(categoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tAno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modeloComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeloComboMousePressed
        switch (marcaCombo.getSelectedItem().toString()) {
            case "VW":
            modeloCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Modelo ---", "Gol", "Kombi", "Nivus"
            }));
            break;
            case "GM":
            modeloCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Modelo ---", "Celta"
            }));
            break;
            case "Fiat":
            modeloCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Modelo ---", "Palio", "Pulse"
            }));
            break;
            case "Honda":
            modeloCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Modelo ---", "BIZ", "TWISTER"
            }));
            break;
            case "Mercedes":
            modeloCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Modelo ---", "Sprinter", "Sedan"
            }));
            break;
            case "Yamaha":
            modeloCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Modelo ---", "FAZER", "CROSSER"
            }));
            break;
            default:
            modeloCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Modelo ---", "Nenhuma Marca foi selecionada"
            }));
        }
    }//GEN-LAST:event_modeloComboMousePressed

    private void categoriaComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaComboMousePressed
        switch (modeloCombo.getSelectedItem().toString()) {
            case "Gol":
            case "Celta":
            case "Kombi":
            case "BIZ":
            case "Palio":
            categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Categoria ---", "POPULAR"
            }));
            break;
            case "FAZER":
            case "CROSSER":
            case "TWISTER":
            case "Sprinter":
            categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Categoria ---", "INTERMEDIARIO"
            }));
            break;
            case "Sedan":
            case "Pulse":
            case "Nivus":
            categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Categoria ---", "LUXO"
            }));
            break;
            default:
            categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
                "--- Selecione Categoria ---", "Nenhum modelo foi selecionado"
            }));
        }
    }//GEN-LAST:event_categoriaComboMousePressed

    public void formataCampo() {
        try {
            MaskFormatter maskA = new MaskFormatter("####");
            MaskFormatter maskV = new MaskFormatter("########");
            MaskFormatter maskP = new MaskFormatter("UUU-####");
            maskP.install(tPlaca);
            maskV.install(tValor);
            maskA.install(tAno);
        } catch (Exception err) {
            JOptionPane.showMessageDialog(this, "ERRO! Algum campo foi mal preenchido!");
        }
    }

    public void limparCampos() {
        marcaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "--- Selecione Marca ---", "VW", "GM", "Fiat", "Honda", "Mercedes", "Yahama"
        }));
        modeloCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "--- Selecione Modelo ---"
        }));
        estadoCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "--- Selecione Estado ---", "DISPONIVEL"
        }));
        categoriaCombo.setModel(new DefaultComboBoxModel<>(new String[]{
            "--- Selecione Categoria ---"
        }));
        tValor.setText("");
        tPlaca.setText("");
        tAno.setText("");
    }
    
    public Veiculo getVeiculoFormulario() {
        Marca marca = Marca.valueOf(marcaCombo.getSelectedItem().toString());
        Estado estado = Estado.valueOf(estadoCombo.getSelectedItem().toString());
        Categoria categoria = Categoria.valueOf(categoriaCombo.getSelectedItem().toString());

        double valor = Double.parseDouble(tValor.getText());
        int ano = Integer.parseInt(tAno.getText());
        String placa = tPlaca.getText();
        String modelo = modeloCombo.getSelectedItem().toString();
        Veiculo veiculo = null;

        switch (modelo) {
            case "Gol":
            case "Celta":
            case "Palio":
            case "Nivus":
            case "Pulse":
            case "Sedan":
                ModeloAutomovel enumA = ModeloAutomovel.valueOf(modelo);
                veiculo = new Automovel(marca, estado, null, categoria, valor, placa, ano, enumA);
                break;
            case "FAZER":
            case "CROSSER":
            case "BIZ":
            case "TWISTER":
                ModeloMotocicleta enumM = ModeloMotocicleta.valueOf(modelo);
                veiculo = new Motocicleta(marca, estado, null, categoria, valor, placa, ano, enumM);
                break;
            case "Kombi":
            case "Sprinter":
                ModeloVan enumV = ModeloVan.valueOf(modelo);
                veiculo = new Van(marca, estado, null, categoria, valor, placa, ano, enumV);
                break;
        }

        return veiculo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoriaCombo;
    private javax.swing.JComboBox<String> estadoCombo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lModelo;
    private javax.swing.JComboBox<String> marcaCombo;
    private javax.swing.JComboBox<String> modeloCombo;
    private javax.swing.JFormattedTextField tAno;
    private javax.swing.JFormattedTextField tPlaca;
    private javax.swing.JFormattedTextField tValor;
    // End of variables declaration//GEN-END:variables
}
