/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view.TelaComprar;

import javax.swing.JOptionPane;
import locadora.controller.VeiculoController;
import locadora.model.Veiculo;

/**
 *
 * @author goldb
 */
public class TelaComprarVeiculoView extends javax.swing.JFrame {

    /**
     * Creates new form NewTelaComprarVeiculoView
     */
    public TelaComprarVeiculoView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioTelaComprarVeiculoView = new locadora.view.TelaComprar.FormularioTelaComprarVeiculoView();
        botaoTelaComprarVeiculoView = new locadora.view.TelaComprar.BotaoTelaComprarVeiculoView();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comprar Veiculo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(formularioTelaComprarVeiculoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoTelaComprarVeiculoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(formularioTelaComprarVeiculoView, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoTelaComprarVeiculoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initView() {
        java.awt.EventQueue.invokeLater(() -> this.setVisible(true));
    }

    public void setController(VeiculoController controller) {
        this.botaoTelaComprarVeiculoView.setController(controller);
    }
    
    public void formataCampo() {
        this.formularioTelaComprarVeiculoView.formataCampo();
    }

    public void limparCampos() {
        this.formularioTelaComprarVeiculoView.limparCampos();
    }
    
    public Veiculo getVeiculoFormulario() {
        return this.formularioTelaComprarVeiculoView.getVeiculoFormulario();
    }
    
    public void apresentaInfo(String info) {
        JOptionPane.showMessageDialog(null, info + "\n", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }

    public void apresentaErro(String erro) {
        JOptionPane.showMessageDialog(null, erro + "\n", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private locadora.view.TelaComprar.BotaoTelaComprarVeiculoView botaoTelaComprarVeiculoView;
    private locadora.view.TelaComprar.FormularioTelaComprarVeiculoView formularioTelaComprarVeiculoView;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
